//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvaluationDetail
    {
        public tblEvaluationDetail()
        {
            this.tblEvaluationResults = new HashSet<tblEvaluationResult>();
        }
    
        public long EvaluationDetailSeqNo { get; set; }
        public long EvaluationNo { get; set; }
        public string Grade { get; set; }
        public string Class { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public System.TimeSpan ScheduledTime { get; set; }
        public string SchoolId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IsActive { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblEvaluationHeader tblEvaluationHeader { get; set; }
        public virtual tblGrade tblGrade { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual ICollection<tblEvaluationResult> tblEvaluationResults { get; set; }
    }
}
