//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvaluationHeader
    {
        public tblEvaluationHeader()
        {
            this.tblEvaluationDetails = new HashSet<tblEvaluationDetail>();
        }
    
        public long EvaluationNo { get; set; }
        public string EvaluationDescription { get; set; }
        public long EvaluationType { get; set; }
        public string AccedamicYear { get; set; }
        public string SchoolId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> TestPaperFee { get; set; }
        public string isActive { get; set; }
    
        public virtual ICollection<tblEvaluationDetail> tblEvaluationDetails { get; set; }
        public virtual tblEvaluationType tblEvaluationType { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
