//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParentToSchoolMessageDetail
    {
        public long SeqNo { get; set; }
        public string SchoolId { get; set; }
        public long MessageId { get; set; }
        public string RecepientUser { get; set; }
        public string Status { get; set; }
        public System.DateTime AuthorizationDate { get; set; }
        public string AuthorizedBy { get; set; }
        public string AuthStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IsActive { get; set; }
    
        public virtual tblParentToSchoolMessageHeader tblParentToSchoolMessageHeader { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
    }
}
