//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchool
    {
        public tblSchool()
        {
            this.tblAssignmentDueDates = new HashSet<tblAssignmentDueDate>();
            this.tblAssignmentHeaders = new HashSet<tblAssignmentHeader>();
            this.tblAssignmentQuestionAids = new HashSet<tblAssignmentQuestionAid>();
            this.tblAssignmentQuestionAnswers = new HashSet<tblAssignmentQuestionAnswer>();
            this.tblAssingmentQuestions = new HashSet<tblAssingmentQuestion>();
            this.tblClasses = new HashSet<tblClass>();
            this.tblClassTeachers = new HashSet<tblClassTeacher>();
            this.tblEntranceApplications = new HashSet<tblEntranceApplication>();
            this.tblEvaluationDetails = new HashSet<tblEvaluationDetail>();
            this.tblEvaluationHeaders = new HashSet<tblEvaluationHeader>();
            this.tblEvaluationResults = new HashSet<tblEvaluationResult>();
            this.tblEventCalendars = new HashSet<tblEventCalendar>();
            this.tblHouses = new HashSet<tblHouse>();
            this.tblParentStudents = new HashSet<tblParentStudent>();
            this.tblParentToSchoolMessageDetails = new HashSet<tblParentToSchoolMessageDetail>();
            this.tblParentToSchoolMessageHeaders = new HashSet<tblParentToSchoolMessageHeader>();
            this.tblSchoolCalendars = new HashSet<tblSchoolCalendar>();
            this.tblSchoolExtraCurricularActivities = new HashSet<tblSchoolExtraCurricularActivity>();
            this.tblSchoolGrades = new HashSet<tblSchoolGrade>();
            this.tblSchoolSubjects = new HashSet<tblSchoolSubject>();
            this.tblSchoolToParentMessageDetails = new HashSet<tblSchoolToParentMessageDetail>();
            this.tblSchoolToParentMessageHeaders = new HashSet<tblSchoolToParentMessageHeader>();
            this.tblStudents = new HashSet<tblStudent>();
            this.tblStudentExtraCurricularActivities = new HashSet<tblStudentExtraCurricularActivity>();
            this.tblStudentOptionalSubjects = new HashSet<tblStudentOptionalSubject>();
            this.tblTeacherExtraCurricularActivities = new HashSet<tblTeacherExtraCurricularActivity>();
            this.tblTeacherExtraCurricularActivities1 = new HashSet<tblTeacherExtraCurricularActivity>();
            this.tblTeacherQualifications = new HashSet<tblTeacherQualification>();
            this.tblTeacherSchools = new HashSet<tblTeacherSchool>();
            this.tblTeacherSubjects = new HashSet<tblTeacherSubject>();
            this.tblTimeTables = new HashSet<tblTimeTable>();
        }
    
        public string SchoolId { get; set; }
        public string SchoolName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string WebUrl { get; set; }
        public string Fax { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> Division { get; set; }
        public Nullable<long> SchoolGroup { get; set; }
        public Nullable<int> SchoolRank { get; set; }
        public string Description { get; set; }
        public string LogoPath { get; set; }
        public string ImagePath { get; set; }
        public int MinuteforPeriod { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public int SchoolCategory { get; set; }
        public string IsActive { get; set; }
    
        public virtual ICollection<tblAssignmentDueDate> tblAssignmentDueDates { get; set; }
        public virtual ICollection<tblAssignmentHeader> tblAssignmentHeaders { get; set; }
        public virtual ICollection<tblAssignmentQuestionAid> tblAssignmentQuestionAids { get; set; }
        public virtual ICollection<tblAssignmentQuestionAnswer> tblAssignmentQuestionAnswers { get; set; }
        public virtual ICollection<tblAssingmentQuestion> tblAssingmentQuestions { get; set; }
        public virtual ICollection<tblClass> tblClasses { get; set; }
        public virtual ICollection<tblClassTeacher> tblClassTeachers { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual tblDivision tblDivision { get; set; }
        public virtual ICollection<tblEntranceApplication> tblEntranceApplications { get; set; }
        public virtual ICollection<tblEvaluationDetail> tblEvaluationDetails { get; set; }
        public virtual ICollection<tblEvaluationHeader> tblEvaluationHeaders { get; set; }
        public virtual ICollection<tblEvaluationResult> tblEvaluationResults { get; set; }
        public virtual ICollection<tblEventCalendar> tblEventCalendars { get; set; }
        public virtual ICollection<tblHouse> tblHouses { get; set; }
        public virtual ICollection<tblParentStudent> tblParentStudents { get; set; }
        public virtual ICollection<tblParentToSchoolMessageDetail> tblParentToSchoolMessageDetails { get; set; }
        public virtual ICollection<tblParentToSchoolMessageHeader> tblParentToSchoolMessageHeaders { get; set; }
        public virtual tblProvince tblProvince { get; set; }
        public virtual tblSchoolCategory tblSchoolCategory { get; set; }
        public virtual tblSchoolGroup tblSchoolGroup { get; set; }
        public virtual tblSchoolRank tblSchoolRank { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual ICollection<tblSchoolCalendar> tblSchoolCalendars { get; set; }
        public virtual ICollection<tblSchoolExtraCurricularActivity> tblSchoolExtraCurricularActivities { get; set; }
        public virtual ICollection<tblSchoolGrade> tblSchoolGrades { get; set; }
        public virtual ICollection<tblSchoolSubject> tblSchoolSubjects { get; set; }
        public virtual ICollection<tblSchoolToParentMessageDetail> tblSchoolToParentMessageDetails { get; set; }
        public virtual ICollection<tblSchoolToParentMessageHeader> tblSchoolToParentMessageHeaders { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblStudentExtraCurricularActivity> tblStudentExtraCurricularActivities { get; set; }
        public virtual ICollection<tblStudentOptionalSubject> tblStudentOptionalSubjects { get; set; }
        public virtual ICollection<tblTeacherExtraCurricularActivity> tblTeacherExtraCurricularActivities { get; set; }
        public virtual ICollection<tblTeacherExtraCurricularActivity> tblTeacherExtraCurricularActivities1 { get; set; }
        public virtual ICollection<tblTeacherQualification> tblTeacherQualifications { get; set; }
        public virtual ICollection<tblTeacherSchool> tblTeacherSchools { get; set; }
        public virtual ICollection<tblTeacherSubject> tblTeacherSubjects { get; set; }
        public virtual ICollection<tblTimeTable> tblTimeTables { get; set; }
    }
}
