//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolMGTEntitiesConnectionString : DbContext
    {
        public SchoolMGTEntitiesConnectionString()
            : base("name=SchoolMGTEntitiesConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblApplicationStatu> tblApplicationStatus { get; set; }
        public DbSet<tblAssignmentDueDate> tblAssignmentDueDates { get; set; }
        public DbSet<tblAssignmentHeader> tblAssignmentHeaders { get; set; }
        public DbSet<tblAssignmentQuestionAid> tblAssignmentQuestionAids { get; set; }
        public DbSet<tblAssignmentQuestionAnswer> tblAssignmentQuestionAnswers { get; set; }
        public DbSet<tblAssignmentQuestionType> tblAssignmentQuestionTypes { get; set; }
        public DbSet<tblAssingmentQuestion> tblAssingmentQuestions { get; set; }
        public DbSet<tblClass> tblClasses { get; set; }
        public DbSet<tblClassTeacher> tblClassTeachers { get; set; }
        public DbSet<tblDistrict> tblDistricts { get; set; }
        public DbSet<tblDivision> tblDivisions { get; set; }
        public DbSet<tblEntranceApplication> tblEntranceApplications { get; set; }
        public DbSet<tblEvaluationDetail> tblEvaluationDetails { get; set; }
        public DbSet<tblEvaluationHeader> tblEvaluationHeaders { get; set; }
        public DbSet<tblEvaluationResult> tblEvaluationResults { get; set; }
        public DbSet<tblEvaluationType> tblEvaluationTypes { get; set; }
        public DbSet<tblEventCalendar> tblEventCalendars { get; set; }
        public DbSet<tblEventcategory> tblEventcategories { get; set; }
        public DbSet<tblEventParticipant> tblEventParticipants { get; set; }
        public DbSet<tblExtraCurricularActivity> tblExtraCurricularActivities { get; set; }
        public DbSet<tblFunction> tblFunctions { get; set; }
        public DbSet<tblGrade> tblGrades { get; set; }
        public DbSet<tblGradeSubject> tblGradeSubjects { get; set; }
        public DbSet<tblHouse> tblHouses { get; set; }
        public DbSet<tblMessageType> tblMessageTypes { get; set; }
        public DbSet<tblParent> tblParents { get; set; }
        public DbSet<tblParentObservationType> tblParentObservationTypes { get; set; }
        public DbSet<tblParentStudent> tblParentStudents { get; set; }
        public DbSet<tblParentToSchoolMessageDetail> tblParentToSchoolMessageDetails { get; set; }
        public DbSet<tblParentToSchoolMessageHeader> tblParentToSchoolMessageHeaders { get; set; }
        public DbSet<tblProvince> tblProvinces { get; set; }
        public DbSet<tblQualification> tblQualifications { get; set; }
        public DbSet<tblRelashionship> tblRelashionships { get; set; }
        public DbSet<tblSchool> tblSchools { get; set; }
        public DbSet<tblSchoolCalendar> tblSchoolCalendars { get; set; }
        public DbSet<tblSchoolCategory> tblSchoolCategories { get; set; }
        public DbSet<tblSchoolExtraCurricularActivity> tblSchoolExtraCurricularActivities { get; set; }
        public DbSet<tblSchoolGrade> tblSchoolGrades { get; set; }
        public DbSet<tblSchoolGroup> tblSchoolGroups { get; set; }
        public DbSet<tblSchoolRank> tblSchoolRanks { get; set; }
        public DbSet<tblSchoolSubject> tblSchoolSubjects { get; set; }
        public DbSet<tblSchoolToParentMessageDetail> tblSchoolToParentMessageDetails { get; set; }
        public DbSet<tblSchoolToParentMessageHeader> tblSchoolToParentMessageHeaders { get; set; }
        public DbSet<tblStudent> tblStudents { get; set; }
        public DbSet<tblStudentExtraCurricularActivity> tblStudentExtraCurricularActivities { get; set; }
        public DbSet<tblStudentOptionalSubject> tblStudentOptionalSubjects { get; set; }
        public DbSet<tblSubject> tblSubjects { get; set; }
        public DbSet<tblSubjectCategory> tblSubjectCategories { get; set; }
        public DbSet<tblTeacher> tblTeachers { get; set; }
        public DbSet<tblTeacherCategory> tblTeacherCategories { get; set; }
        public DbSet<tblTeacherExtraCurricularActivity> tblTeacherExtraCurricularActivities { get; set; }
        public DbSet<tblTeacherQualification> tblTeacherQualifications { get; set; }
        public DbSet<tblTeacherSchool> tblTeacherSchools { get; set; }
        public DbSet<tblTeacherSubject> tblTeacherSubjects { get; set; }
        public DbSet<tblTimeTable> tblTimeTables { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUserCategory> tblUserCategories { get; set; }
        public DbSet<tblUserCategoryFunction> tblUserCategoryFunctions { get; set; }
    }
}
