//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssingmentQuestion
    {
        public long AssingmentNo { get; set; }
        public string SchoolId { get; set; }
        public long QustionId { get; set; }
        public string SubQuestionNo { get; set; }
        public int QuestionType { get; set; }
        public string QuestionNo { get; set; }
        public Nullable<int> LevelId { get; set; }
        public string Question { get; set; }
        public string Hint { get; set; }
        public Nullable<decimal> EntitleMark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> ParentObservationType { get; set; }
        public string ParentDescription { get; set; }
    
        public virtual tblAssignmentQuestionType tblAssignmentQuestionType { get; set; }
        public virtual tblParentObservationType tblParentObservationType { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
