//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentHistory1
    {
        public long SeqNo { get; set; }
        public string AcademicYear { get; set; }
        public string SchoolId { get; set; }
        public string StudentId { get; set; }
        public string GradeId { get; set; }
        public string ClassId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreadedDate { get; set; }
        public string ModifyedBy { get; set; }
        public Nullable<System.DateTime> ModifyedDate { get; set; }
    }
}
