//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolToParentMessageAttachment
    {
        public long SeqNo { get; set; }
        public long MessageId { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentPath { get; set; }
    }
}
