//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolToParentMessageHeader
    {
        public tblSchoolToParentMessageHeader()
        {
            this.tblSchoolToParentMessageDetails = new HashSet<tblSchoolToParentMessageDetail>();
        }
    
        public string SchoolId { get; set; }
        public long MessageId { get; set; }
        public string Subject { get; set; }
        public long MessageType { get; set; }
        public string Message { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IsActive { get; set; }
        public string Sender { get; set; }
    
        public virtual tblMessageType tblMessageType { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual ICollection<tblSchoolToParentMessageDetail> tblSchoolToParentMessageDetails { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
