//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubject
    {
        public tblSubject()
        {
            this.tblAssignmentHeaders = new HashSet<tblAssignmentHeader>();
            this.tblEvaluationResults = new HashSet<tblEvaluationResult>();
            this.tblGradeSubjects = new HashSet<tblGradeSubject>();
            this.tblSchoolSubjects = new HashSet<tblSchoolSubject>();
            this.tblStudentOptionalSubjects = new HashSet<tblStudentOptionalSubject>();
            this.tblTeacherSubjects = new HashSet<tblTeacherSubject>();
            this.tblTimeTables = new HashSet<tblTimeTable>();
        }
    
        public int SubjectId { get; set; }
        public string ShortName { get; set; }
        public string SubjectName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IsActive { get; set; }
    
        public virtual ICollection<tblAssignmentHeader> tblAssignmentHeaders { get; set; }
        public virtual ICollection<tblEvaluationResult> tblEvaluationResults { get; set; }
        public virtual ICollection<tblGradeSubject> tblGradeSubjects { get; set; }
        public virtual ICollection<tblSchoolSubject> tblSchoolSubjects { get; set; }
        public virtual ICollection<tblStudentOptionalSubject> tblStudentOptionalSubjects { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual ICollection<tblTeacherSubject> tblTeacherSubjects { get; set; }
        public virtual ICollection<tblTimeTable> tblTimeTables { get; set; }
    }
}
