//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeTable
    {
        public long SeqNo { get; set; }
        public string AcademicYear { get; set; }
        public string SchoolId { get; set; }
        public string GradeId { get; set; }
        public string ClassId { get; set; }
        public string Day { get; set; }
        public int SubjectId { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IsActive { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblGrade tblGrade { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblSubject tblSubject { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
