//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDWEBSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblAccadamicYears = new HashSet<tblAccadamicYear>();
            this.tblAccadamicYears1 = new HashSet<tblAccadamicYear>();
            this.tblApplicationStatus = new HashSet<tblApplicationStatu>();
            this.tblApplicationStatus1 = new HashSet<tblApplicationStatu>();
            this.tblAssignmentDueDates = new HashSet<tblAssignmentDueDate>();
            this.tblAssignmentDueDates1 = new HashSet<tblAssignmentDueDate>();
            this.tblAssignmentHeaders = new HashSet<tblAssignmentHeader>();
            this.tblAssignmentHeaders1 = new HashSet<tblAssignmentHeader>();
            this.tblAssignmentQuestionAids = new HashSet<tblAssignmentQuestionAid>();
            this.tblAssignmentQuestionAids1 = new HashSet<tblAssignmentQuestionAid>();
            this.tblAssignmentQuestionAnswers = new HashSet<tblAssignmentQuestionAnswer>();
            this.tblAssignmentQuestionAnswers1 = new HashSet<tblAssignmentQuestionAnswer>();
            this.tblAssignmentQuestionTypes = new HashSet<tblAssignmentQuestionType>();
            this.tblAssignmentQuestionTypes1 = new HashSet<tblAssignmentQuestionType>();
            this.tblAssingmentQuestions = new HashSet<tblAssingmentQuestion>();
            this.tblAssingmentQuestions1 = new HashSet<tblAssingmentQuestion>();
            this.tblClasses = new HashSet<tblClass>();
            this.tblClasses1 = new HashSet<tblClass>();
            this.tblClassTeachers = new HashSet<tblClassTeacher>();
            this.tblClassTeachers1 = new HashSet<tblClassTeacher>();
            this.tblDistricts = new HashSet<tblDistrict>();
            this.tblDistricts1 = new HashSet<tblDistrict>();
            this.tblDivisions = new HashSet<tblDivision>();
            this.tblDivisions1 = new HashSet<tblDivision>();
            this.tblEntranceApplications = new HashSet<tblEntranceApplication>();
            this.tblEntranceApplications1 = new HashSet<tblEntranceApplication>();
            this.tblEvaluationDetails = new HashSet<tblEvaluationDetail>();
            this.tblEvaluationDetails1 = new HashSet<tblEvaluationDetail>();
            this.tblEvaluationHeaders = new HashSet<tblEvaluationHeader>();
            this.tblEvaluationHeaders1 = new HashSet<tblEvaluationHeader>();
            this.tblEvaluationResults = new HashSet<tblEvaluationResult>();
            this.tblEvaluationResults1 = new HashSet<tblEvaluationResult>();
            this.tblEvaluationTypes = new HashSet<tblEvaluationType>();
            this.tblEvaluationTypes1 = new HashSet<tblEvaluationType>();
            this.tblEventCalendars = new HashSet<tblEventCalendar>();
            this.tblEventCalendars1 = new HashSet<tblEventCalendar>();
            this.tblEventcategories = new HashSet<tblEventcategory>();
            this.tblEventcategories1 = new HashSet<tblEventcategory>();
            this.tblEventParticipants = new HashSet<tblEventParticipant>();
            this.tblEventParticipants1 = new HashSet<tblEventParticipant>();
            this.tblEventParticipants2 = new HashSet<tblEventParticipant>();
            this.tblExtraCurricularActivities = new HashSet<tblExtraCurricularActivity>();
            this.tblExtraCurricularActivities1 = new HashSet<tblExtraCurricularActivity>();
            this.tblFunctions = new HashSet<tblFunction>();
            this.tblFunctions1 = new HashSet<tblFunction>();
            this.tblGrades = new HashSet<tblGrade>();
            this.tblGrades1 = new HashSet<tblGrade>();
            this.tblGradeSubjects = new HashSet<tblGradeSubject>();
            this.tblGradeSubjects1 = new HashSet<tblGradeSubject>();
            this.tblHouses = new HashSet<tblHouse>();
            this.tblHouses1 = new HashSet<tblHouse>();
            this.tblMessageTypes = new HashSet<tblMessageType>();
            this.tblMessageTypes1 = new HashSet<tblMessageType>();
            this.tblParents = new HashSet<tblParent>();
            this.tblParents1 = new HashSet<tblParent>();
            this.tblParentObservationTypes = new HashSet<tblParentObservationType>();
            this.tblParentObservationTypes1 = new HashSet<tblParentObservationType>();
            this.tblParentStudents = new HashSet<tblParentStudent>();
            this.tblParentStudents1 = new HashSet<tblParentStudent>();
            this.tblParentToSchoolMessageDetails = new HashSet<tblParentToSchoolMessageDetail>();
            this.tblParentToSchoolMessageDetails1 = new HashSet<tblParentToSchoolMessageDetail>();
            this.tblParentToSchoolMessageDetails2 = new HashSet<tblParentToSchoolMessageDetail>();
            this.tblParentToSchoolMessageDetails3 = new HashSet<tblParentToSchoolMessageDetail>();
            this.tblParentToSchoolMessageHeaders = new HashSet<tblParentToSchoolMessageHeader>();
            this.tblParentToSchoolMessageHeaders1 = new HashSet<tblParentToSchoolMessageHeader>();
            this.tblProvinces = new HashSet<tblProvince>();
            this.tblProvinces1 = new HashSet<tblProvince>();
            this.tblQualifications = new HashSet<tblQualification>();
            this.tblQualifications1 = new HashSet<tblQualification>();
            this.tblRelashionships = new HashSet<tblRelashionship>();
            this.tblRelashionships1 = new HashSet<tblRelashionship>();
            this.tblSchools = new HashSet<tblSchool>();
            this.tblSchools1 = new HashSet<tblSchool>();
            this.tblSchoolCalendars = new HashSet<tblSchoolCalendar>();
            this.tblSchoolCalendars1 = new HashSet<tblSchoolCalendar>();
            this.tblSchoolCategories = new HashSet<tblSchoolCategory>();
            this.tblSchoolCategories1 = new HashSet<tblSchoolCategory>();
            this.tblSchoolExtraCurricularActivities = new HashSet<tblSchoolExtraCurricularActivity>();
            this.tblSchoolExtraCurricularActivities1 = new HashSet<tblSchoolExtraCurricularActivity>();
            this.tblSchoolGrades = new HashSet<tblSchoolGrade>();
            this.tblSchoolGrades1 = new HashSet<tblSchoolGrade>();
            this.tblSchoolGroups = new HashSet<tblSchoolGroup>();
            this.tblSchoolGroups1 = new HashSet<tblSchoolGroup>();
            this.tblSchoolRanks = new HashSet<tblSchoolRank>();
            this.tblSchoolRanks1 = new HashSet<tblSchoolRank>();
            this.tblSchoolSubjects = new HashSet<tblSchoolSubject>();
            this.tblSchoolSubjects1 = new HashSet<tblSchoolSubject>();
            this.tblSchoolToParentMessageDetails = new HashSet<tblSchoolToParentMessageDetail>();
            this.tblSchoolToParentMessageDetails1 = new HashSet<tblSchoolToParentMessageDetail>();
            this.tblSchoolToParentMessageHeaders = new HashSet<tblSchoolToParentMessageHeader>();
            this.tblSchoolToParentMessageHeaders1 = new HashSet<tblSchoolToParentMessageHeader>();
            this.tblStudents = new HashSet<tblStudent>();
            this.tblStudents1 = new HashSet<tblStudent>();
            this.tblStudentExtraCurricularActivities = new HashSet<tblStudentExtraCurricularActivity>();
            this.tblStudentExtraCurricularActivities1 = new HashSet<tblStudentExtraCurricularActivity>();
            this.tblStudentOptionalSubjects = new HashSet<tblStudentOptionalSubject>();
            this.tblStudentOptionalSubjects1 = new HashSet<tblStudentOptionalSubject>();
            this.tblSubjects = new HashSet<tblSubject>();
            this.tblSubjects1 = new HashSet<tblSubject>();
            this.tblSubjectCategories = new HashSet<tblSubjectCategory>();
            this.tblSubjectCategories1 = new HashSet<tblSubjectCategory>();
            this.tblTeachers = new HashSet<tblTeacher>();
            this.tblTeachers1 = new HashSet<tblTeacher>();
            this.tblTeacherCategories = new HashSet<tblTeacherCategory>();
            this.tblTeacherCategories1 = new HashSet<tblTeacherCategory>();
            this.tblTeacherExtraCurricularActivities = new HashSet<tblTeacherExtraCurricularActivity>();
            this.tblTeacherExtraCurricularActivities1 = new HashSet<tblTeacherExtraCurricularActivity>();
            this.tblTeacherQualifications = new HashSet<tblTeacherQualification>();
            this.tblTeacherQualifications1 = new HashSet<tblTeacherQualification>();
            this.tblTeacherSchools = new HashSet<tblTeacherSchool>();
            this.tblTeacherSchools1 = new HashSet<tblTeacherSchool>();
            this.tblTeacherSubjects = new HashSet<tblTeacherSubject>();
            this.tblTeacherSubjects1 = new HashSet<tblTeacherSubject>();
            this.tblTimeTables = new HashSet<tblTimeTable>();
            this.tblTimeTables1 = new HashSet<tblTimeTable>();
            this.tblUserCategoryFunctions = new HashSet<tblUserCategoryFunction>();
            this.tblUserCategoryFunctions1 = new HashSet<tblUserCategoryFunction>();
        }
    
        public string UserId { get; set; }
        public string LoginEmail { get; set; }
        public string Password { get; set; }
        public string SchoolId { get; set; }
        public string UserCategory { get; set; }
        public string PersonName { get; set; }
        public string JobDescription { get; set; }
        public string Mobile { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IsActive { get; set; }
    
        public virtual ICollection<tblAccadamicYear> tblAccadamicYears { get; set; }
        public virtual ICollection<tblAccadamicYear> tblAccadamicYears1 { get; set; }
        public virtual ICollection<tblApplicationStatu> tblApplicationStatus { get; set; }
        public virtual ICollection<tblApplicationStatu> tblApplicationStatus1 { get; set; }
        public virtual ICollection<tblAssignmentDueDate> tblAssignmentDueDates { get; set; }
        public virtual ICollection<tblAssignmentDueDate> tblAssignmentDueDates1 { get; set; }
        public virtual ICollection<tblAssignmentHeader> tblAssignmentHeaders { get; set; }
        public virtual ICollection<tblAssignmentHeader> tblAssignmentHeaders1 { get; set; }
        public virtual ICollection<tblAssignmentQuestionAid> tblAssignmentQuestionAids { get; set; }
        public virtual ICollection<tblAssignmentQuestionAid> tblAssignmentQuestionAids1 { get; set; }
        public virtual ICollection<tblAssignmentQuestionAnswer> tblAssignmentQuestionAnswers { get; set; }
        public virtual ICollection<tblAssignmentQuestionAnswer> tblAssignmentQuestionAnswers1 { get; set; }
        public virtual ICollection<tblAssignmentQuestionType> tblAssignmentQuestionTypes { get; set; }
        public virtual ICollection<tblAssignmentQuestionType> tblAssignmentQuestionTypes1 { get; set; }
        public virtual ICollection<tblAssingmentQuestion> tblAssingmentQuestions { get; set; }
        public virtual ICollection<tblAssingmentQuestion> tblAssingmentQuestions1 { get; set; }
        public virtual ICollection<tblClass> tblClasses { get; set; }
        public virtual ICollection<tblClass> tblClasses1 { get; set; }
        public virtual ICollection<tblClassTeacher> tblClassTeachers { get; set; }
        public virtual ICollection<tblClassTeacher> tblClassTeachers1 { get; set; }
        public virtual ICollection<tblDistrict> tblDistricts { get; set; }
        public virtual ICollection<tblDistrict> tblDistricts1 { get; set; }
        public virtual ICollection<tblDivision> tblDivisions { get; set; }
        public virtual ICollection<tblDivision> tblDivisions1 { get; set; }
        public virtual ICollection<tblEntranceApplication> tblEntranceApplications { get; set; }
        public virtual ICollection<tblEntranceApplication> tblEntranceApplications1 { get; set; }
        public virtual ICollection<tblEvaluationDetail> tblEvaluationDetails { get; set; }
        public virtual ICollection<tblEvaluationDetail> tblEvaluationDetails1 { get; set; }
        public virtual ICollection<tblEvaluationHeader> tblEvaluationHeaders { get; set; }
        public virtual ICollection<tblEvaluationHeader> tblEvaluationHeaders1 { get; set; }
        public virtual ICollection<tblEvaluationResult> tblEvaluationResults { get; set; }
        public virtual ICollection<tblEvaluationResult> tblEvaluationResults1 { get; set; }
        public virtual ICollection<tblEvaluationType> tblEvaluationTypes { get; set; }
        public virtual ICollection<tblEvaluationType> tblEvaluationTypes1 { get; set; }
        public virtual ICollection<tblEventCalendar> tblEventCalendars { get; set; }
        public virtual ICollection<tblEventCalendar> tblEventCalendars1 { get; set; }
        public virtual ICollection<tblEventcategory> tblEventcategories { get; set; }
        public virtual ICollection<tblEventcategory> tblEventcategories1 { get; set; }
        public virtual ICollection<tblEventParticipant> tblEventParticipants { get; set; }
        public virtual ICollection<tblEventParticipant> tblEventParticipants1 { get; set; }
        public virtual ICollection<tblEventParticipant> tblEventParticipants2 { get; set; }
        public virtual ICollection<tblExtraCurricularActivity> tblExtraCurricularActivities { get; set; }
        public virtual ICollection<tblExtraCurricularActivity> tblExtraCurricularActivities1 { get; set; }
        public virtual ICollection<tblFunction> tblFunctions { get; set; }
        public virtual ICollection<tblFunction> tblFunctions1 { get; set; }
        public virtual ICollection<tblGrade> tblGrades { get; set; }
        public virtual ICollection<tblGrade> tblGrades1 { get; set; }
        public virtual ICollection<tblGradeSubject> tblGradeSubjects { get; set; }
        public virtual ICollection<tblGradeSubject> tblGradeSubjects1 { get; set; }
        public virtual ICollection<tblHouse> tblHouses { get; set; }
        public virtual ICollection<tblHouse> tblHouses1 { get; set; }
        public virtual ICollection<tblMessageType> tblMessageTypes { get; set; }
        public virtual ICollection<tblMessageType> tblMessageTypes1 { get; set; }
        public virtual ICollection<tblParent> tblParents { get; set; }
        public virtual ICollection<tblParent> tblParents1 { get; set; }
        public virtual ICollection<tblParentObservationType> tblParentObservationTypes { get; set; }
        public virtual ICollection<tblParentObservationType> tblParentObservationTypes1 { get; set; }
        public virtual ICollection<tblParentStudent> tblParentStudents { get; set; }
        public virtual ICollection<tblParentStudent> tblParentStudents1 { get; set; }
        public virtual ICollection<tblParentToSchoolMessageDetail> tblParentToSchoolMessageDetails { get; set; }
        public virtual ICollection<tblParentToSchoolMessageDetail> tblParentToSchoolMessageDetails1 { get; set; }
        public virtual ICollection<tblParentToSchoolMessageDetail> tblParentToSchoolMessageDetails2 { get; set; }
        public virtual ICollection<tblParentToSchoolMessageDetail> tblParentToSchoolMessageDetails3 { get; set; }
        public virtual ICollection<tblParentToSchoolMessageHeader> tblParentToSchoolMessageHeaders { get; set; }
        public virtual ICollection<tblParentToSchoolMessageHeader> tblParentToSchoolMessageHeaders1 { get; set; }
        public virtual ICollection<tblProvince> tblProvinces { get; set; }
        public virtual ICollection<tblProvince> tblProvinces1 { get; set; }
        public virtual ICollection<tblQualification> tblQualifications { get; set; }
        public virtual ICollection<tblQualification> tblQualifications1 { get; set; }
        public virtual ICollection<tblRelashionship> tblRelashionships { get; set; }
        public virtual ICollection<tblRelashionship> tblRelashionships1 { get; set; }
        public virtual ICollection<tblSchool> tblSchools { get; set; }
        public virtual ICollection<tblSchool> tblSchools1 { get; set; }
        public virtual ICollection<tblSchoolCalendar> tblSchoolCalendars { get; set; }
        public virtual ICollection<tblSchoolCalendar> tblSchoolCalendars1 { get; set; }
        public virtual ICollection<tblSchoolCategory> tblSchoolCategories { get; set; }
        public virtual ICollection<tblSchoolCategory> tblSchoolCategories1 { get; set; }
        public virtual ICollection<tblSchoolExtraCurricularActivity> tblSchoolExtraCurricularActivities { get; set; }
        public virtual ICollection<tblSchoolExtraCurricularActivity> tblSchoolExtraCurricularActivities1 { get; set; }
        public virtual ICollection<tblSchoolGrade> tblSchoolGrades { get; set; }
        public virtual ICollection<tblSchoolGrade> tblSchoolGrades1 { get; set; }
        public virtual ICollection<tblSchoolGroup> tblSchoolGroups { get; set; }
        public virtual ICollection<tblSchoolGroup> tblSchoolGroups1 { get; set; }
        public virtual ICollection<tblSchoolRank> tblSchoolRanks { get; set; }
        public virtual ICollection<tblSchoolRank> tblSchoolRanks1 { get; set; }
        public virtual ICollection<tblSchoolSubject> tblSchoolSubjects { get; set; }
        public virtual ICollection<tblSchoolSubject> tblSchoolSubjects1 { get; set; }
        public virtual ICollection<tblSchoolToParentMessageDetail> tblSchoolToParentMessageDetails { get; set; }
        public virtual ICollection<tblSchoolToParentMessageDetail> tblSchoolToParentMessageDetails1 { get; set; }
        public virtual ICollection<tblSchoolToParentMessageHeader> tblSchoolToParentMessageHeaders { get; set; }
        public virtual ICollection<tblSchoolToParentMessageHeader> tblSchoolToParentMessageHeaders1 { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblStudent> tblStudents1 { get; set; }
        public virtual ICollection<tblStudentExtraCurricularActivity> tblStudentExtraCurricularActivities { get; set; }
        public virtual ICollection<tblStudentExtraCurricularActivity> tblStudentExtraCurricularActivities1 { get; set; }
        public virtual ICollection<tblStudentOptionalSubject> tblStudentOptionalSubjects { get; set; }
        public virtual ICollection<tblStudentOptionalSubject> tblStudentOptionalSubjects1 { get; set; }
        public virtual ICollection<tblSubject> tblSubjects { get; set; }
        public virtual ICollection<tblSubject> tblSubjects1 { get; set; }
        public virtual ICollection<tblSubjectCategory> tblSubjectCategories { get; set; }
        public virtual ICollection<tblSubjectCategory> tblSubjectCategories1 { get; set; }
        public virtual ICollection<tblTeacher> tblTeachers { get; set; }
        public virtual ICollection<tblTeacher> tblTeachers1 { get; set; }
        public virtual ICollection<tblTeacherCategory> tblTeacherCategories { get; set; }
        public virtual ICollection<tblTeacherCategory> tblTeacherCategories1 { get; set; }
        public virtual ICollection<tblTeacherExtraCurricularActivity> tblTeacherExtraCurricularActivities { get; set; }
        public virtual ICollection<tblTeacherExtraCurricularActivity> tblTeacherExtraCurricularActivities1 { get; set; }
        public virtual ICollection<tblTeacherQualification> tblTeacherQualifications { get; set; }
        public virtual ICollection<tblTeacherQualification> tblTeacherQualifications1 { get; set; }
        public virtual ICollection<tblTeacherSchool> tblTeacherSchools { get; set; }
        public virtual ICollection<tblTeacherSchool> tblTeacherSchools1 { get; set; }
        public virtual ICollection<tblTeacherSubject> tblTeacherSubjects { get; set; }
        public virtual ICollection<tblTeacherSubject> tblTeacherSubjects1 { get; set; }
        public virtual ICollection<tblTimeTable> tblTimeTables { get; set; }
        public virtual ICollection<tblTimeTable> tblTimeTables1 { get; set; }
        public virtual ICollection<tblUserCategoryFunction> tblUserCategoryFunctions { get; set; }
        public virtual ICollection<tblUserCategoryFunction> tblUserCategoryFunctions1 { get; set; }
    }
}
